### ISSUE TITLE
Cannot reproduce sample picture

### ISSUE THREAD

**Issue by peterparnes** [TheRealMJP/DXRPathTracer#2]
Thank you for an interesting demo!

I am trying to reproduce the sample picture but the best I get is still jittery. Shouldn't the picture converge in the end to a "perfect" image? What settings where used for the sample image? 

I am running this on a 2080Ti but that shouldn't make any difference, right? 

![dxrpathtracer](https://user-images.githubusercontent.com/439035/47951505-d0a38800-df61-11e8-9bb2-a256ca65ef92.jpg)

**Comment by TheRealMJP** [comment]
Hi Peter!

In theory the image *should* converge as you add more samples, assuming that I don't have any bugs in my code (which I certainly might!). I only used unbiased sampling techniques, so adding additional samples should never introduce more variance. However depending on the lighting paths involved and the degree of mismatch between the lighting and the functions used for importance sampling, it may take many many samples (perhaps more than the 100^2 supported by my demo) in order to reduce the variance to a level where the noise is no longer visible. 

One issue that I noticed and fixed in [2b69247](https://github.com/TheRealMJP/DXRPathTracer/commit/2b69247c722bc44644033ac2876543fc54041ecc) was that I was using a texture with a format of DXGI_FORMAT_R16G16B16A16_FLOAT to accumulate the progressively-rendered results. 16-bit precision was causing significant rounding errors for higher sample counts (since the "lerp" factor gets smaller for each successive sample), so I switched that texture to a full 32-bit precision float format.  So if you don't have that change, I would pull it down if you're going to use high sample counts.

Other than that, you should be able to reproduce my image by moving the sun so that it matches the angle I used. Unfortunately I didn't save the settings I used, so I'm not sure of the exact azimuth + elevation that I used. But you can see that I angled it so that it came through the windows on the left. I believe that I used a sample count of 64^2 for the render, but I don't remember for sure. If you look closely you can see that my image still has some visible noise, so I'm not sure how many more samples it would have needed in order for the noise to be invisible.

**Comment by peterparnes** [comment]
Thank you for the very detailed answer!
